### ISSUE TITLE
Language: Arduino

### ISSUE THREAD

**Issue by Sh4rk-Byte** [spenserblack/gengo#211]
### Name

Arduino

### Popularity

- [X] This language is reasonably popular

### Interpreters / shebangs

- gcc
- arduino-cli

### Extensions

- ino

**Comment by spenserblack** [comment]
I probably need to clarify the "interpreters" section, since it's caused confusion before.

But is placing a shebang a common practice for Arduino files?
```c
#!/bin/gcc
// like this?
```

AFAIK it's compiled, not interpreted, right?

Anyway, thanks for the information! I'll give you a chance if you want to make a PR yourself, otherwise I'll add this in later this week.

@all-contributors add @Sh4rk-Byte for data

**Comment by spenserblack** [comment]
Copying the suggested color from https://github.com/o2sh/onefetch/issues/1171#issuecomment-1723523883:
`#189ba1`
